export default {
  bins: [
    {
      fileName: "South-Ayrshire.jpg",
      slug: "south-ayrshire",
      localAuthorityCountry: "sct",
      localAuthorityCode: "GLG",
      collectionDate: "9 November 2021",
      contributorHandle: "@StephanieKrus",
      contributorURL: "https://twitter.com/StephanieKrus",
      colour: "220-blue",
      councilName: "South Ayrshire",
    },
    {
      fileName: "Clackmannanshire.jpg",
      slug: "clackmannanshire",
      localAuthorityCountry: "sct",
      localAuthorityCode: "GLG",
      collectionDate: "7 November 2021",
      contributorHandle: "@thnurg",
      contributorURL: "https://twitter.com/thnurg",
      colour: "220-blue",
      councilName: "Clackmannanshire",
    },
    {
      fileName: "Central-Bedfordshire.jpg",
      slug: "central-bedfordshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "EHA",
      collectionDate: "9 October 2021",
      colour: "357-green",
      councilName: "Central Bedfordshire",
    },
    {
      fileName: "Bedford.jpg",
      slug: "bedford",
      localAuthorityCountry: "eng",
      localAuthorityCode: "EHA",
      collectionDate: "9 October 2021",
      colour: "780-grayscale",
      councilName: "Bedford",
    },
    {
      fileName: "Eden.jpg",
      slug: "eden",
      localAuthorityCountry: "eng",
      localAuthorityCode: "KES",
      collectionDate: "2 October 2021",
      contributorHandle: "Rachel Kirvan",
      colour: "352-green",
      councilName: "Eden",
    },
    {
      fileName: "Cornwall.jpg",
      slug: "cornwall",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "2 October 2021",
      contributorHandle: "@Amy_Hupe",
      contributorURL: "https://twitter.com/Amy_Hupe",
      colour: "630-brown",
      councilName: "Cornwall",
    },
    {
      fileName: "Worcester.jpg",
      slug: "worcester",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "26 September 2021",
      contributorHandle: "Sharon Walton",
      colour: "601-brown",
      councilName: "Worcester",
    },
    {
      fileName: "Gosport.jpg",
      slug: "gosport",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "31 August 2021",
      contributorHandle: "@rlcjones",
      contributorURL: "https://www.instagram.com/rlcjones",
      colour: "772-grayscale",
      councilName: "Gosport",
    },
    {
      fileName: "Selby.jpg",
      slug: "selby",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "26 August 2021",
      contributorHandle: "@resnikov359",
      contributorURL: "https://www.instagram.com/resnikov359",
      colour: "601-brown",
      councilName: "Selby",
    },
    {
      fileName: "Erewash.jpg",
      slug: "erewash",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "24 August 2021",
      contributorHandle: "@beffdizzle",
      contributorURL: "https://twitter.com/beffdizzle",
      colour: "601-brown",
      councilName: "Erewash",
    },
    {
      fileName: "Redbridge.jpg",
      slug: "redbridge",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "21 August 2021",
      contributorHandle: "@thewub",
      contributorURL: "https://twitter.com/thewub",
      colour: "772-grayscale",
      councilName: "Redbridge",
    },
    {
      fileName: "Wychavon.jpg",
      slug: "wychavon",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "18 August 2021",
      contributorHandle: "@rlcjones",
      contributorURL: "https://twitter.com/rlcjones",
      colour: "720-grayscale",
      councilName: "Wychavon",
    },
    {
      fileName: "Scarborough.jpg",
      slug: "scarborough",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "16 August 2021",
      contributorHandle: "@dimdom",
      contributorURL: "https://twitter.com/dimdom",
      colour: "600-brown",
      councilName: "Scarborough",
    },
    {
      fileName: "West-Lindsey.jpg",
      slug: "west-lindsey",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BPC",
      collectionDate: "16 August 2021",
      contributorHandle: "William",
      colour: "742-grayscale",
      councilName: "West Lindsey",
    },
    {
      fileName: "Warwick.jpg",
      slug: "warwick",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BPC",
      collectionDate: "16 August 2021",
      contributorHandle: "Jeremy Pope",
      colour: "320-green",
      councilName: "Warwick",
    },
    {
      fileName: "Dumfries-and-Galloway.jpg",
      slug: "dumfries-and-galloway",
      localAuthorityCountry: "sct",
      localAuthorityCode: "IVC",
      collectionDate: "15 August 2021",
      contributorHandle: "@StruanSocial",
      contributorURL: "https://twitter.com/StruanSocial",
      colour: "762-grayscale",
      councilName: "Dumfries and Galloway",
    },
    {
      fileName: "Breckland.jpg",
      slug: "breckland",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "14 August 2021",
      contributorHandle: "@liz545",
      contributorURL: "https://twitter.com/liz545",
      colour: "746-grayscale",
      councilName: "Breckland",
    },
    {
      fileName: "Scottish-borders.jpg",
      slug: "scottish-borders",
      localAuthorityCountry: "sct",
      localAuthorityCode: "IVC",
      collectionDate: "13 August 2021",
      contributorHandle: "Ally",
      colour: "733-grayscale",
      councilName: "Scottish Borders",
    },
    {
      fileName: "Ribble-valley.jpg",
      slug: "ribble-valley",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "13 August 2021",
      contributorHandle: "@stuwilky",
      contributorURL: "https://twitter.com/stuwilky",
      colour: "762-grayscale",
      councilName: "Ribble Valley",
    },
    {
      fileName: "Lichfield.jpg",
      slug: "lichfield",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "13 August 2021",
      contributorHandle: "@pezholio",
      contributorURL: "http://twitter.com/pezholio",
      colour: "220-blue",
      councilName: "Lichfield",
    },
    {
      fileName: "Bournemouth-Christchurch-and-Poole.jpg",
      slug: "bournemouth-christchurch-and-poole",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BPC",
      collectionDate: "12 August 2021",
      contributorHandle: "Matt Cheetham",
      colour: "772-grayscale",
      councilName: "Bournemouth, Christchurch and Poole",
    },
    {
      fileName: "Stoke-on-Trent.jpg",
      slug: "stoke-on-trent",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "12 August 2021",
      contributorHandle: "@Nickoli",
      contributorURL: "http://www.twitter.com/Nickoli",
      colour: "724-grayscale",
      councilName: "Stoke-on-Trent",
    },
    {
      fileName: "Stratford-on-Avon.jpg",
      slug: "stratford-on-avon",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "12 August 2021",
      contributorHandle: "@maleo",
      contributorURL: "https://twitter.com/maleo",
      colour: "341-green",
      councilName: "Stratford-on-Avon",
    },
    {
      fileName: "Ryedale.jpg",
      slug: "ryedale",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "9 August 2021",
      contributorHandle: "@alicebartlett",
      contributorURL: "https://twitter.com/alicebartlett",
      colour: "326-green",
      councilName: "Ryedale",
    },
    {
      fileName: "Burnley.jpg",
      slug: "burnley",
      localAuthorityCountry: "eng",
      localAuthorityCode: "FOE",
      collectionDate: "16 July 2021",
      contributorHandle: "@siamakamini",
      contributorURL: "https://www.instagram.com/siamakamini/",
      colour: "503-red-burgundy",
      councilName: "Burnley",
    },
    {
      fileName: "Blaenau-Gwent.jpg",
      slug: "blaenau-gwent",
      localAuthorityCountry: "wls",
      localAuthorityCode: "HAT",
      collectionDate: "30 May 2021",
      colour: "722-grayscale",
      councilName: "Blaenau Gwent",
    },
    {
      fileName: "Monmouthshire.jpg",
      slug: "monmouthshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HAT",
      collectionDate: "29 May 2021",
      colour: "762-grayscale",
      councilName: "Monmouthshire",
    },
    {
      fileName: "North-Ayrshire.jpg",
      slug: "north-ayrshire",
      localAuthorityCountry: "sct",
      localAuthorityCode: "IVC",
      collectionDate: "24 May 2021",
      contributorHandle: "jeni lennox",
      colour: "772-grayscale",
      councilName: "North Ayrshire",
    },
    {
      fileName: "Thurrock.jpg",
      slug: "thurrock",
      localAuthorityCountry: "eng",
      localAuthorityCode: "PEM",
      collectionDate: "20 May 2021",
      contributorHandle: "Anonymous",
      colour: "245-blue",
      councilName: "Thurrock",
    },
    {
      fileName: "Broadland.jpg",
      slug: "broadland",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SNO",
      collectionDate: "18 May 2021",
      contributorHandle: "Stan Hutcheon",
      colour: "731-grayscale",
      councilName: "Broadland",
    },
    {
      fileName: "Pembrokeshire.jpg",
      slug: "pembrokeshire",
      localAuthorityCountry: "wls",
      localAuthorityCode: "PEM",
      collectionDate: "29 April 2021",
      contributorHandle: "Sam D'Ambrosio",
      colour: "507-red-burgundy",
      councilName: "Pembrokeshire",
    },
    {
      fileName: "South-Norfolk.jpg",
      slug: "south-norfolk",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SNO",
      collectionDate: "24 April 2021",
      contributorHandle: "Stan Hutcheon",
      colour: "762-grayscale",
      councilName: "South Norfolk",
    },
    {
      fileName: "Hart.jpg",
      slug: "hart",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HAT",
      collectionDate: "24 April 2021",
      colour: "318-green",
      councilName: "Hart",
    },
    {
      fileName: "East-Hampshire.jpg",
      slug: "east-hampshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "EHA",
      collectionDate: "24 April 2021",
      colour: "357-green",
      councilName: "East Hampshire",
    },
    {
      fileName: "South-Kesteven.jpg",
      slug: "south-kesteven",
      localAuthorityCountry: "eng",
      localAuthorityCode: "KES",
      collectionDate: "20 April 2021",
      contributorHandle: "Rachel Kirvan",
      colour: "762-grayscale",
      councilName: "South Kesteven",
    },
    {
      fileName: "Buckinghamshire.jpg",
      slug: "buckinghamshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BUC",
      collectionDate: "19 April 2021",
      contributorHandle: "@benunsworth",
      contributorURL: "https://twitter.com/benunsworth",
      colour: "601-brown",
      councilName: "Buckinghamshire",
    },
    {
      fileName: "Mendip.jpg",
      slug: "mendip",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MEN",
      collectionDate: "15 April 2021",
      colour: "601-brown",
      councilName: "Mendip",
    },
    {
      fileName: "Dorset.jpg",
      slug: "dorset",
      localAuthorityCountry: "eng",
      localAuthorityCode: "DOR",
      collectionDate: "5 March 2021",
      colour: "780-grayscale",
      councilName: "Dorset",
    },
    {
      fileName: "Teignbridge.jpg",
      slug: "teignbridge",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TEI",
      collectionDate: "28 February 2021",
      colour: "780-grayscale",
      councilName: "Teignbridge",
    },
    {
      fileName: "Torbay.jpg",
      slug: "torbay",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TOB",
      collectionDate: "28 February 2021",
      colour: "318-green",
      councilName: "Torbay",
    },
    {
      fileName: "South-Hams.jpg",
      slug: "south-hams",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SHA",
      collectionDate: "28 February 2021",
      colour: "601-brown",
      councilName: "South Hams",
    },
    {
      fileName: "Herefordshire.jpg",
      slug: "herefordshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HEF",
      collectionDate: "26 February 2021",
      contributorHandle: "@philgyford",
      contributorURL: "https://twitter.com/philgyford",
      colour: "762-grayscale",
      councilName: "Herefordshire",
    },
    {
      fileName: "East-Devon.jpg",
      slug: "east-devon",
      localAuthorityCountry: "eng",
      localAuthorityCode: "EDE",
      collectionDate: "21 February 2021",
      colour: "318-green",
      councilName: "East Devon",
    },
    {
      fileName: "Mid-and-East-Antrim.jpg",
      slug: "mid-and-east-antrim",
      localAuthorityCountry: "ni",
      localAuthorityCode: "MEA",
      collectionDate: "5 February 2021",
      contributorHandle: "@Leebeard1",
      contributorURL: "https://twitter.com/Leebeard1",
      colour: "220-blue",
      councilName: "Mid and East Antrim",
    },
    {
      fileName: "Vale-of-White-Horse.jpg",
      slug: "vale-of-white-horse",
      localAuthorityCountry: "eng",
      localAuthorityCode: "VAL",
      collectionDate: "31 January 2021",
      colour: "615-brown",
      councilName: "Vale of White Horse",
    },
    {
      fileName: "Swindon.jpg",
      slug: "swindon",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SWD",
      collectionDate: "31 January 2021",
      colour: "786-grayscale",
      councilName: "Swindon",
    },
    {
      fileName: "Haringey.jpg",
      slug: "haringey",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HRY",
      collectionDate: "16 January 2021",
      contributorHandle: "@colleybros",
      contributorURL: "https://www.instagram.com/colleybros",
      colour: "734-grayscale",
      councilName: "Haringey",
    },
    {
      fileName: "Craven.jpg",
      slug: "craven",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CRA",
      collectionDate: "8 January 2021",
      contributorHandle: "@annemariebremner5355",
      contributorURL: "https://www.instagram.com/annemariebremner5355",
      colour: "220-blue",
      councilName: "Craven",
    },
    {
      fileName: "Macclesfield.jpg",
      slug: "macclesfield",
      retro: "true",
      retroWhy: "abolished",
      retroName: "Macclesfield",
      presentTwinFileName: "Cheshire-East.jpg",
      startDate: "1974",
      endDate: "2009",
      contributorHandle: "@alicebartlett",
      contributorURL: "https://twitter.com/alicebartlett",
    },
    {
      fileName: "Hart-retro.jpg",
      slug: "hart-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "Hart",
      presentTwinFileName: "Hart.jpg",
      endDate: "2008",
    },
    {
      fileName: "West-Wiltshire.jpg",
      slug: "west-wiltshire",
      retro: "true",
      retroWhy: "abolished",
      retroName: "West Wiltshire",
      presentTwinFileName: "Wiltshire.jpg",
      startDate: "1974",
      endDate: "2009",
      contributorHandle: "@m.sergison",
      contributorURL: "https://www.instagram.com/m.sergison",
    },
    {
      fileName: "Liverpool-retro.jpg",
      slug: "liverpool-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "Liverpool",
      presentTwinFileName: "Liverpool.jpg",
      endDate: "2014",
    },
    {
      fileName: "Southwark-retro.jpg",
      slug: "southwark-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "Southwark",
      presentTwinFileName: "Southwark.jpg",
      endDate: "1999",
    },
    {
      fileName: "Poole.jpg",
      slug: "Poole",
      retro: "true",
      retroWhy: "abolished",
      retroName: "Poole",
      presentTwinFileName: "Bournemouth-Christchurch-and-Poole.jpg",
      startDate: "1974",
      endDate: "2019",
    },
    {
      fileName: "Shepway.jpg",
      slug: "shepway",
      retro: "true",
      retroWhy: "abolished",
      retroName: "Shepway",
      presentTwinFileName: "Folkestone-and-Hythe.jpg",
      startDate: "1974",
      endDate: "2018",
    },
    {
      fileName: "Berwick-upon-Tweed.jpg",
      slug: "berwick-upon-tweed",
      retro: "true",
      retroWhy: "abolished",
      retroName: "Berwick-upon-Tweed",
      presentTwinFileName: "Northumberland.jpg",
      startDate: "1974",
      endDate: "2009",
    },
    {
      fileName: "Purbeck.jpg",
      slug: "purbeck",
      retro: "true",
      retroWhy: "abolished",
      retroName: "Purbeck",
      presentTwinFileName: "Dorset.jpg",
      startDate: "1974",
      endDate: "2019",
    },
    {
      fileName: "North-Wiltshire.jpg",
      slug: "north-wiltshire",
      retro: "true",
      retroWhy: "abolished",
      retroName: "North Wiltshire",
      presentTwinFileName: "Wiltshire.jpg",
      startDate: "1974",
      endDate: "2009",
    },
    {
      fileName: "Haringey-retro.jpg",
      slug: "haringey-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "Haringey",
      presentTwinFileName: "Haringey.jpg",
      endDate: "2015",
    },
    {
      fileName: "Chelmsford-retro.jpg",
      slug: "chelmsford-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "Chelmsford",
      presentTwinFileName: "Chelmsford.jpg",
      endDate: "2012",
    },
    {
      fileName: "Wyre-retro.jpg",
      slug: "wyre-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "Wyre",
      presentTwinFileName: "Wyre.jpg",
      endDate: "1974",
    },
    {
      fileName: "Gloucester-retro.jpg",
      slug: "gloucester-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "Gloucester",
      presentTwinFileName: "Gloucester.jpg",
      endDate: "2012",
    },
    {
      fileName: "Reigate-and-Banstead-retro.jpg",
      slug: "reigate-and-banstead-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "Reigate and Banstead",
      presentTwinFileName: "Reigate-and-Banstead.jpg",
      endDate: "TBC",
    },
    {
      fileName: "Lancaster-retro.jpg",
      slug: "lancaster-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "Lancaster",
      presentTwinFileName: "Lancaster.jpg",
      endDate: "2014",
    },
    {
      fileName: "Kingston-upon-Thames-retro.jpg",
      slug: "kingston-upon-thames-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "Kingston upon Thames",
      presentTwinFileName: "Kingston-upon-Thames.jpg",
      endDate: "2014",
    },
    {
      fileName: "North-Devon-retro.jpg",
      slug: "north-devon-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "North Devon",
      presentTwinFileName: "North-Devon.jpg",
      endDate: "2009",
    },
    {
      fileName: "Castle-Morpeth.jpg",
      slug: "castle-morpeth",
      retro: "true",
      retroWhy: "abolished",
      retroName: "Castle Morpeth",
      presentTwinFileName: "Northumberland.jpg",
      startDate: "1974",
      endDate: "2009",
    },
    {
      fileName: "Bath-and-North-East-Somerset-retro.jpg",
      slug: "bath-and-north-east-somerset-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "Bath and North East Somerset",
      presentTwinFileName: "Bath-and-North-East-Somerset.jpg",
      endDate: "2008",
    },
    {
      fileName: "Wycombe.jpg",
      slug: "wycombe",
      retro: "true",
      retroWhy: "abolished",
      retroName: "Wycombe",
      presentTwinFileName: "Buckinghamshire.jpg",
      startDate: "1974",
      endDate: "2020",
    },
    {
      fileName: "Chiltern.jpg",
      slug: "chiltern",
      retro: "true",
      retroWhy: "abolished",
      retroName: "Chiltern",
      presentTwinFileName: "Buckinghamshire.jpg",
      startDate: "1974",
      endDate: "2020",
    },
    {
      fileName: "South-Bucks.jpg",
      slug: "south-bucks",
      retro: "true",
      retroWhy: "abolished",
      retroName: "South Bucks",
      presentTwinFileName: "Buckinghamshire.jpg",
      startDate: "1974",
      endDate: "2020",
    },
    {
      fileName: "Aylesbury-Vale.jpg",
      slug: "aylesbury-vale",
      retro: "true",
      retroWhy: "abolished",
      retroName: "Aylesbury Vale",
      presentTwinFileName: "Buckinghamshire.jpg",
      startDate: "1974",
      endDate: "2020",
    },
    {
      fileName: "Torbay-retro.jpg",
      slug: "torbay-retro",
      retro: "true",
      retroWhy: "branding",
      retroName: "Torbay",
      presentTwinFileName: "Torbay.jpg",
      endDate: "2020",
    },
    {
      fileName: "West-Dorset.jpg",
      slug: "west-dorset",
      retro: "true",
      retroWhy: "abolished",
      retroName: "West-Dorset",
      presentTwinFileName: "Dorset.jpg",
      startDate: "1974",
      endDate: "2019",
    },
    {
      fileName: "Congleton.jpg",
      slug: "congleton",
      retro: "true",
      retroWhy: "abolished",
      retroName: "Congleton",
      presentTwinFileName: "Cheshire-East.jpg",
      startDate: "1974",
      endDate: "2009",
      contributorHandle: "@paulemorgan",
      contributorURL: "https://www.instagram.com/paulemorgan/",
    },
    {
      fileName: "North-Shropshire.jpg",
      slug: "north-shropshire",
      retro: "true",
      retroWhy: "abolished",
      retroName: "North Shropshire",
      presentTwinFileName: "Shropshire.jpg",
      startDate: "1972",
      endDate: "2009",
      contributorHandle: "@allanwin",
      contributorURL: "https://twitter.com/allanwin",
    },
    {
      fileName: "West-Lancashire.jpg",
      slug: "west-lancashire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WLA",
      collectionDate: "2 January 2021",
      contributorHandle: "@harry.marston",
      contributorURL: "https://instagram.com/harry.marston",
      colour: "200-blue",
      councilName: "West Lancashire",
    },
    {
      fileName: "Basildon.jpg",
      slug: "basildon",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BAI",
      collectionDate: "8 December 2020",
      contributorHandle: "@llpeachyd",
      contributorURL: "https://instagram.com/llpeachyd",
      colour: "325-green",
      councilName: "Basildon",
    },
    {
      fileName: "Tendring.jpg",
      slug: "tendring",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TEN",
      collectionDate: "6 December 2020",
      contributorHandle: "Rachel Kirvan",
      colour: "762-grayscale",
      councilName: "Tendring",
    },
    {
      fileName: "Kettering.jpg",
      slug: "kettering",
      localAuthorityCountry: "eng",
      localAuthorityCode: "KET",
      collectionDate: "16 November 2020",
      contributorHandle: "@toshenhoff",
      contributorURL: "https://twitter.com/toshenhoff",
      colour: "220-blue",
      councilName: "Kettering",
    },
    {
      fileName: "Halton.jpg",
      slug: "halton",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HAL",
      collectionDate: "14 November 2020",
      contributorHandle: "@buddaboy",
      contributorURL: "https://twitter.com/buddaboy",
      colour: "220-blue",
      councilName: "Halton",
    },
    {
      fileName: "Cotswold.jpg",
      slug: "cotswold",
      localAuthorityCountry: "eng",
      localAuthorityCode: "COT",
      collectionDate: "24 October 2020",
      colour: "325-green",
      councilName: "Cotswold",
    },
    {
      fileName: "Inverclyde.jpg",
      slug: "inverclyde",
      localAuthorityCountry: "sct",
      localAuthorityCode: "IVC",
      collectionDate: "22 October 2020",
      contributorHandle: "@jamesmckechni_",
      contributorURL: "https://twitter.com/jamesmckechni_",
      colour: "600-brown",
      councilName: "Inverclyde",
    },
    {
      fileName: "High-Peak.jpg",
      slug: "high-peak",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HIG",
      collectionDate: "13 October 2020",
      contributorHandle: "@ifranco_29",
      contributorURL: "https://twitter.com/ifranco_29",
      colour: "615-brown",
      councilName: "High Peak",
    },
    {
      fileName: "Highland.jpg",
      slug: "highland",
      localAuthorityCountry: "sct",
      localAuthorityCode: "HLD",
      collectionDate: "12 October 2020",
      contributorHandle: "@JoStraw1",
      contributorURL: "https://twitter.com/JoStraw1",
      colour: "325-green",
      councilName: "Highland",
    },
    {
      fileName: "Gwynedd.jpg",
      slug: "gwynedd",
      localAuthorityCountry: "wls",
      localAuthorityCode: "GWN",
      contributorHandle: "@keithemmerson",
      contributorURL: "https://twitter.com/keithemmerson",
      collectionDate: "1 October 2020",
      colour: "600-brown",
      councilName: "Gwynedd",
    },
    {
      fileName: "Derby.jpg",
      slug: "derby",
      localAuthorityCountry: "eng",
      localAuthorityCode: "DER",
      collectionDate: "29 September 2020",
      contributorHandle: "@beamer_boi",
      contributorURL: "https://twitter.com/beamer_boi",
      colour: "220-blue",
      councilName: "Derby",
    },
    {
      fileName: "Tewkesbury.jpg",
      slug: "tewkesbury",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TEW",
      collectionDate: "27 September 2020",
      colour: "260-blue",
      councilName: "Tewkesbury",
    },
    {
      fileName: "Gloucester.jpg",
      slug: "gloucester",
      localAuthorityCountry: "eng",
      localAuthorityCode: "GLO",
      collectionDate: "27 September 2020",
      colour: "762-grayscale",
      councilName: "Gloucester",
    },
    {
      fileName: "Fife.jpg",
      slug: "fife",
      localAuthorityCountry: "sct",
      localAuthorityCode: "FIF",
      collectionDate: "18 September 2020",
      contributorHandle: "@tausendberlin31",
      contributorURL: "https://instagram.com/tausendberlin31",
      colour: "755-grayscale",
      councilName: "Fife",
    },
    {
      fileName: "Barnsley.jpg",
      slug: "barnsley",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BNS",
      collectionDate: "16 September 2020",
      contributorHandle: "@sirskelton",
      contributorURL: "https://www.instagram.com/sirskelton",
      colour: "310-green",
      councilName: "Barnsley",
    },
    {
      fileName: "North-Norfolk.jpg",
      slug: "north-norfolk",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NNO",
      collectionDate: "12 September 2020",
      contributorHandle: "@alicebartlett",
      contributorURL: "https://twitter.com/alicebartlett",
      colour: "750-grayscale",
      councilName: "North Norfolk",
    },
    {
      fileName: "Malvern-Hills.jpg",
      slug: "malvern-hills",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MAV",
      collectionDate: "11 September 2020",
      contributorHandle: "@sillypunk",
      contributorURL: "https://instagram.com/sillypunk",
      colour: "720-grayscale",
      councilName: "Malvern Hills",
    },
    {
      fileName: "Merthyr-Tydfil.jpg",
      slug: "merthyr-tydfil",
      localAuthorityCountry: "wls",
      localAuthorityCode: "MTY",
      collectionDate: "6 September 2020",
      colour: "762-grayscale",
      councilName: "Merthyr Tydfil",
    },
    {
      fileName: "Neath-Port-Talbot.jpg",
      slug: "neath-port-talbot",
      localAuthorityCountry: "wls",
      localAuthorityCode: "NTL",
      collectionDate: "5 September 2020",
      colour: "755-grayscale",
      councilName: "Neath Port Talbot",
    },
    {
      fileName: "Argyll-and-Bute.jpg",
      slug: "argyll-and-bute",
      localAuthorityCountry: "sct",
      localAuthorityCode: "AGB",
      collectionDate: "4 September 2020",
      contributorHandle: "Finlay Wilson",
      colour: "291-blue",
      councilName: "Argyll and Bute",
    },
    {
      fileName: "Aberdeen-City.jpg",
      slug: "aberdeen-city",
      localAuthorityCountry: "sct",
      localAuthorityCode: "ABE",
      collectionDate: "3 September 2020",
      contributorHandle: "@tausendberlin31",
      contributorURL: "https://instagram.com/tausendberlin31",
      colour: "755-grayscale",
      councilName: "Aberdeen City",
    },
    {
      fileName: "Fenland.jpg",
      slug: "fenland",
      localAuthorityCountry: "eng",
      localAuthorityCode: "FEN",
      collectionDate: "2 September 2020",
      contributorHandle: "Oliver Knights",
      colour: "326-green",
      councilName: "Fenland",
    },
    {
      fileName: "Colchester.jpg",
      slug: "colchester",
      localAuthorityCountry: "eng",
      localAuthorityCode: "COL",
      collectionDate: "28 August 2020",
      contributorHandle: "@gazaston",
      contributorURL: "https://twitter.com/gazaston",
      colour: "725-grayscale",
      councilName: "Colchester",
    },
    {
      fileName: "South-Staffordshire.jpg",
      slug: "south-staffordshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SST",
      collectionDate: "26 August 2020",
      contributorHandle: "@DangerMonk1485",
      contributorURL: "https://twitter.com/DangerMonk1485",
      colour: "220-blue",
      councilName: "South Staffordshire",
    },
    {
      fileName: "Aberdeenshire.jpg",
      slug: "aberdeenshire",
      localAuthorityCountry: "sct",
      localAuthorityCode: "ABD",
      collectionDate: "24 August 2020",
      contributorHandle: "@Mike_Rawlins",
      contributorURL: "https://twitter.com/Mike_Rawlins",
      colour: "776-grayscale",
      councilName: "Aberdeenshire",
    },
    {
      fileName: "Flintshire.jpg",
      slug: "flintshire",
      localAuthorityCountry: "wls",
      localAuthorityCode: "FLN",
      collectionDate: "24 August 2020",
      contributorHandle: "@Louis_g._",
      contributorURL: "https://www.instagram.com/Louis_g._/",
      colour: "791-grayscale",
      councilName: "Flintshire",
    },
    {
      fileName: "Orkney-Islands.jpg",
      slug: "orkney-islands",
      localAuthorityCountry: "sct",
      localAuthorityCode: "ORK",
      collectionDate: "24 August 2020",
      contributorHandle: "@sweynh",
      contributorURL: "https://twitter.com/sweynh",
      colour: "325-green",
      councilName: "Orkney Islands",
    },
    {
      fileName: "Sheffield.jpg",
      slug: "sheffield",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SHF",
      collectionDate: "23 August 2020",
      contributorHandle: "Melissa Young",
      colour: "600-brown",
      councilName: "Sheffield",
    },
    {
      fileName: "Torridge.jpg",
      slug: "torridge",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TOR",
      collectionDate: "22 August 2020",
      contributorHandle: "Hugh Blackman",
      colour: "329-green",
      councilName: "Torridge",
    },
    {
      fileName: "Derbyshire-Dales.jpg",
      slug: "derbyshire-dales",
      localAuthorityCountry: "eng",
      localAuthorityCode: "DEB",
      collectionDate: "22 August 2020",
      contributorHandle: "Samatha Podmore",
      colour: "775-grayscale",
      councilName: "Derbyshire Dales",
    },
    {
      fileName: "West-Oxfordshire.jpg",
      slug: "west-oxfordshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WOX",
      collectionDate: "22 August 2020",
      contributorHandle: "Anonymous",
      colour: "795-grayscale",
      councilName: "West Oxfordshire",
    },
    {
      fileName: "Mid-Suffolk.jpg",
      slug: "mid-suffolk",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MSU",
      collectionDate: "22 August 2020",
      contributorHandle: "@camillaherrmann",
      contributorURL: "https://www.instagram.com/camillaherrmann",
      colour: "725-grayscale",
      councilName: "Mid Suffolk",
    },
    {
      fileName: "North-Lanarkshire.jpg",
      slug: "north-lanarkshire",
      localAuthorityCountry: "sct",
      localAuthorityCode: "NLK",
      collectionDate: "22 August 2020",
      contributorHandle: "Peter Munns",
      colour: "642-brown",
      councilName: "North Lanarkshire",
    },
    {
      fileName: "Calderdale.jpg",
      slug: "calderdale",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CLD",
      collectionDate: "10 August 2020",
      contributorHandle: "@Holland_pie",
      contributorURL: "https://www.instagram.com/Holland_pie",
      colour: "725-grayscale",
      councilName: "Calderdale",
    },
    {
      fileName: "North-East-Lincolnshire.jpg",
      slug: "north-east-lincolnshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NEL",
      collectionDate: "5 August 2020",
      contributorHandle: "@bin_lorry_fan_uk",
      contributorURL: "https://www.instagram.com/bin_lorry_fan_uk/",
      colour: "355-green",
      councilName: "North East Lincolnshire",
    },
    {
      fileName: "North-Lincolnshire.jpg",
      slug: "north-lincolnshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NLN",
      collectionDate: "3 August 2020",
      contributorHandle: "@bin_lorry_fan_uk",
      contributorURL: "https://www.instagram.com/bin_lorry_fan_uk/",
      colour: "503-red-burgundy",
      councilName: "North Lincolnshire",
    },
    {
      fileName: "South-Derbyshire.jpg",
      slug: "south-derbyshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SDE",
      collectionDate: "18 July 2020",
      contributorHandle: "Helen Campbell",
      colour: "313-green",
      councilName: "South Derbyshire",
    },
    {
      fileName: "Amber-Valley.jpg",
      slug: "amber-valley",
      localAuthorityCountry: "eng",
      localAuthorityCode: "AMB",
      collectionDate: "18 July 2020",
      contributorHandle: "Helen Campbell",
      colour: "762-grayscale",
      councilName: "Amber Valley",
    },
    {
      fileName: "Lisburn-and-Castlereagh.jpg",
      slug: "lisburn-and-castlereagh",
      localAuthorityCountry: "ni",
      localAuthorityCode: "LBC",
      collectionDate: "18 July 2020",
      contributorHandle: "@patrick_s_k",
      contributorURL: "https://www.instagram.com/patrick_s_k",
      colour: "310-green",
      councilName: "Lisburn and Castlereagh City",
    },
    {
      fileName: "Somerset-West-and-Taunton.jpg",
      slug: "somerset-west-and-taunton",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SWT",
      collectionDate: "12 July 2020",
      contributorHandle: "@georgewg323",
      contributorURL: "https://www.instagram.com/georgewg323/",
      colour: "772-grayscale",
      councilName: "Somerset West and Taunton",
    },
    {
      fileName: "Winchester.jpg",
      slug: "winchester",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WIN",
      collectionDate: "11 July 2020",
      colour: "788-grayscale",
      councilName: "Winchester",
    },
    {
      fileName: "Eastleigh.jpg",
      slug: "eastleigh",
      localAuthorityCountry: "eng",
      localAuthorityCode: "EAT",
      collectionDate: "11 July 2020",
      colour: "342-green",
      councilName: "Eastleigh",
    },
    {
      fileName: "Southampton.jpg",
      slug: "southampton",
      localAuthorityCountry: "eng",
      localAuthorityCode: "STH",
      collectionDate: "11 July 2020",
      colour: "321-green",
      councilName: "Southampton",
    },
    {
      fileName: "Forest-of-Dean.jpg",
      slug: "forest-of-dean",
      localAuthorityCountry: "eng",
      localAuthorityCode: "FOE",
      collectionDate: "8 July 2020",
      contributorHandle: "@siamakamini",
      contributorURL: "https://www.instagram.com/siamakamini/",
      colour: "782-grayscale",
      councilName: "Forest of Dean",
    },
    {
      fileName: "Cheltenham.jpg",
      slug: "cheltenham",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CHT",
      collectionDate: "7 July 2020",
      contributorHandle: "@siamakamini",
      contributorURL: "https://www.instagram.com/siamakamini/",
      colour: "600-brown",
      councilName: "Cheltenham",
    },
    {
      fileName: "Belfast.jpg",
      slug: "belfast",
      localAuthorityCountry: "ni",
      localAuthorityCode: "BFS",
      collectionDate: "21 May 2020",
      contributorHandle: "@candaharcats",
      contributorURL: "https://www.instagram.com/candaharcats/",
      colour: "220-blue",
      councilName: "Belfast City",
    },
    {
      fileName: "Falkirk.jpg",
      slug: "falkirk",
      localAuthorityCountry: "sct",
      localAuthorityCode: "FAL",
      collectionDate: "16 May 2020",
      contributorHandle: "@declancorcoran",
      contributorURL: "https://www.instagram.com/declancorcoran/",
      colour: "503-red-burgundy",
      councilName: "Falkirk",
    },
    {
      fileName: "Powys.jpg",
      slug: "powys",
      localAuthorityCountry: "wls",
      localAuthorityCode: "POW",
      collectionDate: "15 May 2020",
      contributorHandle: "@benaldo",
      contributorURL: "https://twitter.com/benaldo/",
      colour: "791-grayscale",
      councilName: "Powys",
    },
    {
      fileName: "East-Suffolk.jpg",
      slug: "east-suffolk",
      localAuthorityCountry: "eng",
      localAuthorityCode: "ESK",
      collectionDate: "3 May 2020",
      contributorHandle: "@angusmontgomery",
      contributorURL: "https://www.instagram.com/angusmontgomery/",
      colour: "643-brown",
      councilName: "East Suffolk",
    },
    {
      fileName: "Bassetlaw.jpg",
      slug: "bassetlaw",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BAE",
      collectionDate: "3 May 2020",
      contributorHandle: "@huwrobinson",
      contributorURL: "https://www.instagram.com/huwrobinson/",
      colour: "220-blue",
      councilName: "Bassetlaw",
    },
    {
      fileName: "Bradford.jpg",
      slug: "bradford",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BRD",
      collectionDate: "3 May 2020",
      contributorHandle: "@neogwydian",
      contributorURL: "https://www.instagram.com/neogwydian/",
      colour: "733-grayscale",
      councilName: "Bradford",
    },
    {
      fileName: "City-of-Lincoln.jpg",
      slug: "city-of-lincoln",
      localAuthorityCountry: "eng",
      localAuthorityCode: "LIC",
      collectionDate: "27 April 2020",
      contributorHandle: "@nacnudus",
      contributorURL: "https://twitter.com/nacnudus",
      colour: "326-green",
      councilName: "City of Lincoln",
    },
    {
      fileName: "Portsmouth.jpg",
      slug: "portsmouth",
      localAuthorityCountry: "eng",
      localAuthorityCode: "POR",
      collectionDate: "26 April 2020",
      contributorHandle: "@loveyourbin",
      contributorURL: "https://www.instagram.com/loveyourbin/",
      colour: "780-grayscale",
      councilName: "Portsmouth",
    },
    {
      fileName: "Doncaster.jpg",
      slug: "doncaster",
      localAuthorityCountry: "eng",
      localAuthorityCode: "DNC",
      collectionDate: "25 April 2020",
      contributorHandle: "@marynagaf",
      contributorURL: "https://www.instagram.com/marynagaf/",
      colour: "245-blue",
      councilName: "Doncaster",
    },
    {
      fileName: "Cheshire-West-and-Chester.jpg",
      slug: "cheshire-west-and-chester",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CHW",
      collectionDate: "25 April 2020",
      contributorHandle: "@paulemorgan",
      contributorURL: "https://www.instagram.com/paulemorgan/",
      colour: "779-grayscale",
      councilName: "Cheshire West and Chester",
    },
    {
      fileName: "Telford-and-Wrekin.jpg",
      slug: "telford-and-wrekin",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TFW",
      collectionDate: "24 April 2020",
      contributorHandle: "@lucyjudson",
      contributorURL: "https://www.instagram.com/lucyjudson/",
      colour: "731-grayscale",
      councilName: "Telford and Wrekin",
    },
    {
      fileName: "Angus.jpg",
      slug: "angus",
      localAuthorityCountry: "sct",
      localAuthorityCode: "ANS",
      collectionDate: "22 April 2020",
      contributorHandle: "@simdess",
      contributorURL: "https://twitter.com/simdess",
      colour: "111-purple",
      councilName: "Angus",
    },
    {
      fileName: "Kings-Lynn-and-West-Norfolk.jpg",
      slug: "kings-lynn-and-west-norfolk",
      localAuthorityCountry: "eng",
      localAuthorityCode: "KIN",
      collectionDate: "21 April 2020",
      contributorHandle: "@mrdanielweir",
      contributorURL: "https://www.instagram.com/mrdanielweir/",
      colour: "773-grayscale",
      councilName: "King's Lynn and West Norfolk",
    },
    {
      fileName: "North-Devon.jpg",
      slug: "north-devon",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NDE",
      collectionDate: "19 April 2020",
      contributorHandle: "@vosageroll",
      contributorURL: "https://twitter.com/vosageroll",
      colour: "755-grayscale",
      councilName: "North Devon",
    },
    {
      fileName: "Stroud.jpg",
      slug: "stroud",
      localAuthorityCountry: "eng",
      localAuthorityCode: "STO",
      collectionDate: "18 April 2020",
      contributorHandle: "@joegiddings",
      contributorURL: "https://twitter.com/joegiddings",
      colour: "772-grayscale",
      councilName: "Stroud",
    },
    {
      fileName: "East-Riding-of-Yorkshire.jpg",
      slug: "east-riding-of-yorkshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "ERY",
      collectionDate: "18 April 2020",
      contributorHandle: "@fezlayd",
      contributorURL: "https://www.instagram.com/fezlayd",
      colour: "351-green",
      councilName: "East Riding of Yorkshire",
    },
    {
      fileName: "Wakefield.jpg",
      slug: "wakefield",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WKF",
      collectionDate: "13 April 2020",
      contributorHandle: "@taikodrum",
      contributorURL: "https://www.instagram.com/taikodrum",
      colour: "624-brown",
      councilName: "Wakefield",
    },
    {
      fileName: "East-Lindsey.jpg",
      slug: "east-lindsey",
      localAuthorityCountry: "eng",
      localAuthorityCode: "ELI",
      collectionDate: "13 April 2020",
      contributorHandle: "@tronkins",
      contributorURL: "https://www.instagram.com/tronkins",
      colour: "720-grayscale",
      councilName: "East Lindsey",
    },
    {
      fileName: "Cheshire-East.jpg",
      slug: "cheshire-east",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CHE",
      collectionDate: "12 March 2020",
      colour: "709-grayscale",
      councilName: "Cheshire East",
    },
    {
      fileName: "Coventry.jpg",
      slug: "coventry",
      localAuthorityCountry: "eng",
      localAuthorityCode: "COV",
      collectionDate: "5 March 2020",
      colour: "314-green",
      councilName: "Coventry",
    },
    {
      fileName: "Bromsgrove.jpg",
      slug: "bromsgrove",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BRM",
      collectionDate: "5 March 2020",
      colour: "799-grayscale",
      councilName: "Bromsgrove",
    },
    {
      fileName: "Rushmoor.jpg",
      slug: "rushmoor",
      localAuthorityCountry: "eng",
      localAuthorityCode: "RUH",
      collectionDate: "28 February 2020",
      colour: "210-blue",
      councilName: "Rushmoor",
    },
    {
      fileName: "Antrim-and-Newtownabbey.jpg",
      slug: "antrim-and-newtownabbey",
      localAuthorityCountry: "ni",
      localAuthorityCode: "ANN",
      councilName: "Antrim and Newtownabbey",
      collectionDate: "27 February 2020",
      colour: "220-blue",
      councilName: "Antrim and Newtownabbey",
    },
    {
      fileName: "Conwy.jpg",
      slug: "conwy",
      localAuthorityCountry: "wls",
      localAuthorityCode: "CWY",
      collectionDate: "25 February 2020",
      contributorHandle: "@SarahBargiela",
      contributorURL: "https://twitter.com/SarahBargiela",
      colour: "742-grayscale",
      councilName: "Conwy",
    },
    {
      fileName: "Arun.jpg",
      slug: "arun",
      localAuthorityCountry: "eng",
      localAuthorityCode: "ARU",
      collectionDate: "15 February 2020",
      colour: "351-green",
      councilName: "Arun",
    },
    {
      fileName: "Adur-and-Worthing.jpg",
      slug: "adur-and-worthing",
      councilName: "Adur and Worthing",
      collectionDate: "15 February 2020",
      colour: "777-grayscale",
      councilName: "Adur and Worthing",
    },
    {
      fileName: "Chichester.jpg",
      slug: "chichester",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CHI",
      collectionDate: "15 February 2020",
      colour: "506-red-burgundy",
      councilName: "Chichester",
    },
    {
      fileName: "Horsham.jpg",
      slug: "horsham",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HOR",
      collectionDate: "15 February 2020",
      colour: "351-green",
      councilName: "Horsham",
    },
    {
      fileName: "Crawley.jpg",
      slug: "crawley",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CRW",
      collectionDate: "15 February 2020",
      colour: "314-green",
      councilName: "Crawley",
    },
    {
      fileName: "Eastbourne.jpg",
      slug: "eastbourne",
      localAuthorityCountry: "eng",
      localAuthorityCode: "EAS",
      collectionDate: "8 February 2020",
      colour: "748-grayscale",
      councilName: "Eastbourne",
    },
    {
      fileName: "Wealden.jpg",
      slug: "wealden",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WEA",
      collectionDate: "8 February 2020",
      colour: "315-green",
      councilName: "Wealden",
    },
    {
      fileName: "Lewes.jpg",
      slug: "lewes",
      localAuthorityCountry: "eng",
      localAuthorityCode: "LEE",
      collectionDate: "8 February 2020",
      colour: "322-green",
      councilName: "Lewes",
    },
    {
      fileName: "Solihull.jpg",
      slug: "solihull",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SOL",
      collectionDate: "5 February 2020",
      colour: "762-grayscale",
      councilName: "Solihull",
    },
    {
      fileName: "Sandwell.jpg",
      slug: "sandwell",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SAW",
      collectionDate: "5 February 2020",
      colour: "310-green",
      councilName: "Sandwell",
    },
    {
      fileName: "Wolverhampton.jpg",
      slug: "wolverhampton",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WLV",
      collectionDate: "5 February 2020",
      colour: "621-brown",
      councilName: "Wolverhampton",
    },
    {
      fileName: "Sevenoaks.jpg",
      slug: "sevenoaks",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SEV",
      collectionDate: "26 January 2020",
      colour: "321-green",
      councilName: "Sevenoaks",
    },
    {
      fileName: "North-Somerset.jpg",
      slug: "north-somerset",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NSM",
      collectionDate: "12 January 2020",
      colour: "356-green",
      councilName: "North Somerset",
    },
    {
      fileName: "Southwark.jpg",
      slug: "southwark",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SWK",
      collectionDate: "2 January 2020",
      colour: "318-green",
      councilName: "Southwark",
    },
    {
      fileName: "Thanet.jpg",
      slug: "thanet",
      localAuthorityCountry: "eng",
      localAuthorityCode: "THA",
      collectionDate: "30 December 2019",
      colour: "755-grayscale",
      councilName: "Thanet",
    },
    {
      fileName: "Canterbury.jpg",
      slug: "canterbury",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CAT",
      collectionDate: "30 December 2019",
      colour: "341-green",
      councilName: "Canterbury",
    },
    {
      fileName: "Swale.jpg",
      slug: "swale",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SWL",
      collectionDate: "30 December 2019",
      colour: "210-blue",
      councilName: "Swale",
    },
    {
      fileName: "Ashford.jpg",
      slug: "ashford",
      localAuthorityCountry: "eng",
      localAuthorityCode: "ASF",
      collectionDate: "30 December 2019",
      colour: "311-green",
      councilName: "Ashford",
    },
    {
      fileName: "Folkestone-and-Hythe.jpg",
      slug: "folkestone-and-hythe",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SHE",
      collectionDate: "29 December 2019",
      colour: "333-green",
      councilName: "Folkestone and Hythe",
    },
    {
      fileName: "Dover.jpg",
      slug: "dover",
      localAuthorityCountry: "eng",
      localAuthorityCode: "DOV",
      collectionDate: "29 December 2019",
      colour: "781-grayscale",
      councilName: "Dover",
    },
    {
      fileName: "Uttlesford.jpg",
      slug: "uttlesford",
      localAuthorityCountry: "eng",
      localAuthorityCode: "UTT",
      collectionDate: "17 December 2019",
      colour: "794-grayscale",
      councilName: "Uttlesford",
    },
    {
      fileName: "South-Gloucestershire.jpg",
      slug: "south-gloucestershire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SGC",
      collectionDate: "8 December 2019",
      colour: "787-grayscale",
      councilName: "South Gloucestershire",
    },
    {
      fileName: "Somerset.jpg",
      slug: "somerset",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SOM",
      collectionDate: "7 December 2019",
      colour: "749-grayscale",
      councilName: "Somerset",
    },
    {
      fileName: "Brentwood.jpg",
      slug: "brentwood",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BRW",
      collectionDate: "29 November 2019",
      colour: "210-blue",
      councilName: "Brentwood",
    },
    {
      fileName: "Chelmsford.jpg",
      slug: "chelmsford",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CHL",
      collectionDate: "23 November 2019",
      colour: "733-grayscale",
      councilName: "Chelmsford",
    },
    {
      fileName: "Maldon.jpg",
      slug: "maldon",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MAL",
      collectionDate: "23 November 2019",
      colour: "750-grayscale",
      councilName: "Maldon",
    },
    {
      fileName: "Braintree.jpg",
      slug: "braintree",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BRA",
      collectionDate: "23 November 2019",
      colour: "500-red-burgundy",
      councilName: "Braintree",
    },
    {
      fileName: "Derry-City-and-Strabane.jpg",
      slug: "derry-city-and-strabane",
      localAuthorityCountry: "ni",
      localAuthorityCode: "DRS",
      councilName: "Derry City and Strabane",
      collectionDate: "22 October 2019",
      colour: "610-brown",
      councilName: "Derry City and Strabane",
    },
    {
      fileName: "Test-Valley.jpg",
      slug: "test-valley",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TES",
      collectionDate: "5 October 2019",
      colour: "777-grayscale",
      councilName: "Test Valley",
    },
    {
      fileName: "Basingstoke-and-Deane.jpg",
      slug: "basingstoke-and-deane",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BAN",
      collectionDate: "5 October 2019",
      colour: "325-green",
      councilName: "Basingstoke and Deane",
    },
    {
      fileName: "Stevenage.jpg",
      slug: "stevenage",
      localAuthorityCountry: "eng",
      localAuthorityCode: "STV",
      collectionDate: "25 September 2019",
      colour: "620-brown",
      councilName: "Stevenage",
    },
    {
      fileName: "North-Hertfordshire.jpg",
      slug: "north-hertfordshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NHE",
      collectionDate: "25 September 2019",
      colour: "100-purple",
      councilName: "North Hertfordshire",
    },
    {
      fileName: "Harlow.jpg",
      slug: "harlow",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HAR",
      collectionDate: "24 September 2019",
      colour: "785-grayscale",
      councilName: "Harlow",
    },
    {
      fileName: "South-Cambridgeshire.jpg",
      slug: "south-cambridgeshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SCA",
      collectionDate: "21 July 2019",
      colour: "340-green",
      councilName: "South Cambridgeshire",
    },
    {
      fileName: "Cambridge.jpg",
      slug: "cambridge",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CAB",
      collectionDate: "21 July 2019",
      colour: "322-green",
      councilName: "Cambridge",
    },
    {
      fileName: "West-Suffolk.jpg",
      slug: "west-suffolk",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WSK",
      collectionDate: "20 July 2019",
      colour: "245-blue",
      councilName: "West Suffolk",
    },
    {
      fileName: "Welwyn-Hatfield.jpg",
      slug: "welwyn-hatfield",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WEW",
      collectionDate: "20 July 2019",
      colour: "748-grayscale",
      councilName: "Welwyn Hatfield",
    },
    {
      fileName: "Cardiff.jpg",
      slug: "cardiff",
      localAuthorityCountry: "wls",
      localAuthorityCode: "CRF",
      collectionDate: "9 July 2019",
      colour: "732-grayscale",
      councilName: "Cardiff",
    },
    {
      fileName: "Newport.jpg",
      slug: "newport",
      localAuthorityCountry: "wls",
      localAuthorityCode: "NWP",
      collectionDate: "9 July 2019",
      colour: "312-green",
      councilName: "Newport",
    },
    {
      fileName: "Caerphilly.jpg",
      slug: "caerphilly",
      localAuthorityCountry: "wls",
      localAuthorityCode: "CAY",
      collectionDate: "8 July 2019",
      colour: "631-brown",
      councilName: "Caerphilly",
    },
    {
      fileName: "Shropshire.jpg",
      slug: "shropshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SHR",
      collectionDate: "22 June 2019",
      colour: "753-grayscale",
      councilName: "Shropshire",
    },
    {
      fileName: "Carlisle.jpg",
      slug: "carlisle",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CAR",
      collectionDate: "12 June 2019",
      colour: "778-grayscale",
      councilName: "Carlisle",
    },
    {
      fileName: "Leeds.jpg",
      slug: "leeds",
      localAuthorityCountry: "eng",
      localAuthorityCode: "LDS",
      collectionDate: "29 May 2019",
      colour: "783-grayscale",
      councilName: "Leeds",
    },
    {
      fileName: "Sutton.jpg",
      slug: "sutton",
      localAuthorityCountry: "eng",
      localAuthorityCode: "STN",
      collectionDate: "21 May 2019",
      colour: "630-brown",
      councilName: "Sutton",
    },
    {
      fileName: "Rother.jpg",
      slug: "rother",
      localAuthorityCountry: "eng",
      localAuthorityCode: "ROH",
      collectionDate: "16 May 2019",
      colour: "352-green",
      councilName: "Rother",
    },
    {
      fileName: "Hastings.jpg",
      slug: "hastings",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HAS",
      collectionDate: "16 May 2019",
      colour: "351-green",
      councilName: "Hastings",
    },
    {
      fileName: "Midlothian.jpg",
      slug: "midlothian",
      localAuthorityCountry: "sct",
      localAuthorityCode: "MLN",
      collectionDate: "6 May 2019",
      colour: "245-blue",
      councilName: "Midlothian",
    },
    {
      fileName: "East-Lothian.jpg",
      slug: "east-lothian",
      localAuthorityCountry: "sct",
      localAuthorityCode: "ELN",
      collectionDate: "6 May 2019",
      colour: "355-green",
      councilName: "East Lothian",
    },
    {
      fileName: "Edinburgh.jpg",
      slug: "edinburgh",
      localAuthorityCountry: "sct",
      localAuthorityCode: "EDH",
      collectionDate: "6 May 2019",
      colour: "720-grayscale",
      councilName: "Edinburgh",
    },
    {
      fileName: "West-Lothian.jpg",
      slug: "west-lothian",
      localAuthorityCountry: "sct",
      localAuthorityCode: "WLN",
      collectionDate: "6 May 2019",
      colour: "790-grayscale",
      councilName: "West Lothian",
    },
    {
      fileName: "Waverley.jpg",
      slug: "waverley",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WAE",
      collectionDate: "5 May 2019",
      colour: "280-blue",
      councilName: "Waverley",
    },
    {
      fileName: "Greenwich.jpg",
      slug: "greenwich",
      localAuthorityCountry: "eng",
      localAuthorityCode: "GRE",
      collectionDate: "21 April 2019",
      colour: "350-green",
      councilName: "Greenwich",
    },
    {
      fileName: "Blackpool.jpg",
      slug: "blackpool",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BPL",
      collectionDate: "18 April 2019",
      colour: "711-grayscale",
      councilName: "Blackpool",
    },
    {
      fileName: "Wyre.jpg",
      slug: "wyre",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WYR",
      collectionDate: "18 April 2019",
      colour: "760-grayscale",
      councilName: "Wyre",
    },
    {
      fileName: "Fylde.jpg",
      slug: "fylde",
      localAuthorityCountry: "eng",
      localAuthorityCode: "FYL",
      collectionDate: "18 April 2019",
      colour: "210-blue",
      councilName: "Fylde",
    },
    {
      fileName: "York.jpg",
      slug: "york",
      localAuthorityCountry: "eng",
      localAuthorityCode: "YOR",
      collectionDate: "31 March 2019",
      colour: "340-green",
      councilName: "York",
    },
    {
      fileName: "Hambleton.jpg",
      slug: "hambleton",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HAE",
      collectionDate: "29 March 2019",
      colour: "724-grayscale",
      councilName: "Hambleton",
    },
    {
      fileName: "Epping-Forest.jpg",
      slug: "epping-forest",
      localAuthorityCountry: "eng",
      localAuthorityCode: "EPP",
      collectionDate: "17 March 2019",
      colour: "725-grayscale",
      councilName: "Epping Forest",
    },
    {
      fileName: "Westminster.jpg",
      slug: "westminster",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WSM",
      collectionDate: "7 February 2019",
      colour: "736-grayscale",
      councilName: "Westminster",
    },
    {
      fileName: "Norwich.jpg",
      slug: "norwich",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NOW",
      collectionDate: "3 February 2019",
      colour: "202-blue",
      councilName: "Norwich",
    },
    {
      fileName: "East-Cambridgeshire.jpg",
      slug: "east-cambridgeshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "ECA",
      collectionDate: "2 February 2019",
      colour: "752-grayscale",
      councilName: "East Cambridgeshire",
    },
    {
      fileName: "Bath-and-North-East-Somerset.jpg",
      slug: "bath-and-north-east-somerset",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BAS",
      collectionDate: "28 December 2018",
      colour: "793-grayscale",
      councilName: "Bath and North East Somerset",
    },
    {
      fileName: "South-Oxfordshire.jpg",
      slug: "south-oxfordshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SOX",
      collectionDate: "26 December 2018",
      colour: "792-grayscale",
      councilName: "South Oxfordshire",
    },
    {
      fileName: "West-Berkshire.jpg",
      slug: "west-berkshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WBK",
      collectionDate: "26 December 2018",
      colour: "363-green",
      councilName: "West Berkshire",
    },
    {
      fileName: "Reading.jpg",
      slug: "reading",
      localAuthorityCountry: "eng",
      localAuthorityCode: "RDG",
      collectionDate: "26 December 2018",
      colour: "504-red-burgundy",
      councilName: "Reading",
    },
    {
      fileName: "Wokingham.jpg",
      slug: "wokingham",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WOK",
      collectionDate: "26 December 2018",
      colour: "615-brown",
      councilName: "Wokingham",
    },
    {
      fileName: "Bracknell-Forest.jpg",
      slug: "bracknell-forest",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BRC",
      collectionDate: "26 December 2018",
      colour: "220-blue",
      councilName: "Bracknell Forest",
    },
    {
      fileName: "Hounslow.jpg",
      slug: "hounslow",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HNS",
      collectionDate: "24 December 2018",
      colour: "616-brown",
      councilName: "Hounslow",
    },
    {
      fileName: "City-of-Bristol.jpg",
      slug: "city-of-bristol",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BST",
      collectionDate: "2 December 2018",
      colour: "723-grayscale",
      councilName: "City of Bristol",
    },
    {
      fileName: "Exeter.jpg",
      slug: "exeter",
      localAuthorityCountry: "eng",
      localAuthorityCode: "EXE",
      collectionDate: "25 November 2018",
      colour: "505-red-burgundy",
      councilName: "Exeter",
    },
    {
      fileName: "Mid-Devon.jpg",
      slug: "mid-devon",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MDE",
      collectionDate: "25 November 2018",
      colour: "621-brown",
      councilName: "Mid Devon",
    },
    {
      fileName: "Wiltshire.jpg",
      slug: "wiltshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WIL",
      collectionDate: "23 November 2018",
      colour: "721-grayscale",
      councilName: "Wiltshire",
    },
    {
      fileName: "Gateshead.jpg",
      slug: "gateshead",
      localAuthorityCountry: "eng",
      localAuthorityCode: "GAT",
      collectionDate: "21 October 2018",
      colour: "325-green",
      councilName: "Gateshead",
    },
    {
      fileName: "South-Tyneside.jpg",
      slug: "south-tyneside",
      localAuthorityCountry: "eng",
      localAuthorityCode: "STY",
      collectionDate: "21 October 2018",
      colour: "720-grayscale",
      councilName: "South Tyneside",
    },
    {
      fileName: "Sunderland.jpg",
      slug: "sunderland",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SND",
      collectionDate: "21 October 2018",
      colour: "270-blue",
      councilName: "Sunderland",
    },
    {
      fileName: "Hartlepool.jpg",
      slug: "hartlepool",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HPL",
      collectionDate: "21 October 2018",
      colour: "613-brown",
      councilName: "Hartlepool",
    },
    {
      fileName: "Redcar-and-Cleveland.jpg",
      slug: "redcar-and-cleveland",
      localAuthorityCountry: "eng",
      localAuthorityCode: "RCC",
      collectionDate: "21 October 2018",
      colour: "292-blue",
      councilName: "Redcar and Cleveland",
    },
    {
      fileName: "Middlesbrough.jpg",
      slug: "middlesbrough",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MDB",
      collectionDate: "21 October 2018",
      colour: "795-grayscale",
      councilName: "Middlesbrough",
    },
    {
      fileName: "Stockton-on-Tees.jpg",
      slug: "stockton-on-tees",
      localAuthorityCountry: "eng",
      localAuthorityCode: "STT",
      collectionDate: "21 October 2018",
      colour: "320-green",
      councilName: "Stockton-on-Tees",
    },
    {
      fileName: "Darlington.jpg",
      slug: "darlington",
      localAuthorityCountry: "eng",
      localAuthorityCode: "DAL",
      collectionDate: "21 October 2018",
      colour: "755-grayscale",
      councilName: "Darlington",
    },
    {
      fileName: "Richmondshire.jpg",
      slug: "richmondshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "RIH",
      collectionDate: "21 October 2018",
      colour: "764-grayscale",
      councilName: "Richmondshire",
    },
    {
      fileName: "County-Durham.jpg",
      slug: "county-durham",
      localAuthorityCountry: "eng",
      localAuthorityCode: "DUR",
      collectionDate: "21 October 2018",
      colour: "789-grayscale",
      councilName: "County Durham",
    },
    {
      fileName: "City-of-Durham.jpg",
      slug: "city-of-durham",
      councilName: "City of Durham",
      collectionDate: "20 October 2018",
      colour: "748-grayscale",
      councilName: "City of Durham",
    },
    {
      fileName: "Sedgemoor.jpg",
      slug: "sedgemoor",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SEG",
      collectionDate: "6 October 2018",
      colour: "779-grayscale",
      councilName: "Sedgemoor",
    },
    {
      fileName: "Oxford.jpg",
      slug: "oxford",
      localAuthorityCountry: "eng",
      localAuthorityCode: "OXO",
      collectionDate: "12 September 2018",
      colour: "501-red-burgundy",
      councilName: "Oxford",
    },
    {
      fileName: "Islington.jpg",
      slug: "islington",
      localAuthorityCountry: "eng",
      localAuthorityCode: "ISL",
      collectionDate: "24 August 2018",
      colour: "327-green",
      councilName: "Islington",
    },
    {
      fileName: "Kensington-and-Chelsea.jpg",
      slug: "kensington-and-chelsea",
      localAuthorityCountry: "eng",
      localAuthorityCode: "KEC",
      collectionDate: "11 August 2018",
      colour: "280-blue",
      councilName: "Kensington and Chelsea",
    },
    {
      fileName: "Merton.jpg",
      slug: "merton",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MRT",
      collectionDate: "3 June 2018",
      colour: "612-brown",
      councilName: "Merton",
    },
    {
      fileName: "Kingston-upon-Thames.jpg",
      slug: "kingston-upon-thames",
      localAuthorityCountry: "eng",
      localAuthorityCode: "KTT",
      collectionDate: "2 June 2018",
      colour: "749-grayscale",
      councilName: "Kingston upon Thames",
    },
    {
      fileName: "Surrey-Heath.jpg",
      slug: "surrey-heath",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SUR",
      collectionDate: "28 May 2018",
      colour: "342-green",
      councilName: "Surrey Heath",
    },
    {
      fileName: "Woking.jpg",
      slug: "woking",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WOI",
      collectionDate: "28 May 2018",
      colour: "791-grayscale",
      councilName: "Woking",
    },
    {
      fileName: "Runnymede.jpg",
      slug: "runnymede",
      localAuthorityCountry: "eng",
      localAuthorityCode: "RUN",
      collectionDate: "19 May 2018",
      colour: "776-grayscale",
      councilName: "Runnymede",
    },
    {
      fileName: "Camden.jpg",
      slug: "camden",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CMD",
      collectionDate: "16 May 2018",
      colour: "797-grayscale",
      councilName: "Camden",
    },
    {
      fileName: "Tower-Hamlets.jpg",
      slug: "tower-hamlets",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TWH",
      collectionDate: "6 May 2018",
      colour: "101-purple",
      councilName: "Tower Hamlets",
    },
    {
      fileName: "Richmond-upon-Thames.jpg",
      slug: "richmond-upon-thames",
      localAuthorityCountry: "eng",
      localAuthorityCode: "RIC",
      collectionDate: "2 May 2018",
      colour: "331-green",
      councilName: "Richmond upon Thames",
    },
    {
      fileName: "Lewisham.jpg",
      slug: "lewisham",
      localAuthorityCountry: "eng",
      localAuthorityCode: "LEW",
      collectionDate: "29 April 2018",
      colour: "220-blue",
      councilName: "Lewisham",
    },
    {
      fileName: "Croydon.jpg",
      slug: "croydon",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CRY",
      collectionDate: "29 April 2018",
      colour: "751-grayscale",
      councilName: "Croydon",
    },
    {
      fileName: "Bromley.jpg",
      slug: "bromley",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BRY",
      collectionDate: "29 April 2018",
      colour: "796-grayscale",
      councilName: "Bromley",
    },
    {
      fileName: "Newham.jpg",
      slug: "newham",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NWM",
      collectionDate: "29 April 2018",
      colour: "326-green",
      councilName: "Newham",
    },
    {
      fileName: "Windsor-and-Maidenhead.jpg",
      slug: "windsor-and-maidenhead",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WNM",
      collectionDate: "7 April 2018",
      colour: "220-blue",
      councilName: "Windsor and Maidenhead",
    },
    {
      fileName: "Slough.jpg",
      slug: "slough",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SLG",
      collectionDate: "7 April 2018",
      colour: "502-red-burgundy",
      councilName: "Slough",
    },
    {
      fileName: "Nottingham.jpg",
      slug: "nottingham",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NGM",
      collectionDate: "25 March 2018",
      colour: "332-green",
      councilName: "Nottingham",
    },
    {
      fileName: "Broxtowe.jpg",
      slug: "broxtowe",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BRT",
      collectionDate: "25 March 2018",
      colour: "746-grayscale",
      councilName: "Broxtowe",
    },
    {
      fileName: "Rushcliffe.jpg",
      slug: "rushcliffe",
      localAuthorityCountry: "eng",
      localAuthorityCode: "RUS",
      collectionDate: "25 March 2018",
      colour: "210-blue",
      councilName: "Rushcliffe",
    },
    {
      fileName: "Gedling.jpg",
      slug: "gedling",
      localAuthorityCountry: "eng",
      localAuthorityCode: "GED",
      collectionDate: "25 March 2018",
      colour: "503-red-burgundy",
      councilName: "Gedling",
    },
    {
      fileName: "Leicester.jpg",
      slug: "leicester",
      localAuthorityCountry: "eng",
      localAuthorityCode: "LCE",
      collectionDate: "24 March 2018",
      colour: "321-green",
      councilName: "Leicester",
    },
    {
      fileName: "Barnet.jpg",
      slug: "barnet",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BNE",
      collectionDate: "24 March 2018",
      colour: "290-blue",
      councilName: "Barnet",
    },
    {
      fileName: "Bury.jpg",
      slug: "bury",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BUR",
      collectionDate: "17 March 2018",
      colour: "622-brown",
      councilName: "Bury",
    },
    {
      fileName: "Salford.jpg",
      slug: "salford",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SLF",
      collectionDate: "17 March 2018",
      colour: "744-grayscale",
      councilName: "Salford",
    },
    {
      fileName: "Rochdale.jpg",
      slug: "rochdale",
      localAuthorityCountry: "eng",
      localAuthorityCode: "RCH",
      collectionDate: "17 March 2018",
      colour: "220-blue",
      councilName: "Rochdale",
    },
    {
      fileName: "Oldham.jpg",
      slug: "oldham",
      localAuthorityCountry: "eng",
      localAuthorityCode: "OLD",
      collectionDate: "17 March 2018",
      colour: "600-brown",
      councilName: "Oldham",
    },
    {
      fileName: "Tameside.jpg",
      slug: "tameside",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TAM",
      collectionDate: "17 March 2018",
      colour: "634-brown",
      councilName: "Tameside",
    },
    {
      fileName: "Stockport.jpg",
      slug: "stockport",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SKP",
      collectionDate: "17 March 2018",
      colour: "353-green",
      councilName: "Stockport",
    },
    {
      fileName: "Manchester.jpg",
      slug: "manchester",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MAN",
      collectionDate: "17 March 2018",
      colour: "626-brown",
      councilName: "Manchester",
    },
    {
      fileName: "Trafford.jpg",
      slug: "trafford",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TRF",
      collectionDate: "17 March 2018",
      colour: "324-green",
      councilName: "Trafford",
    },
    {
      fileName: "Wigan.jpg",
      slug: "wigan",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WGN",
      collectionDate: "16 March 2018",
      colour: "220-blue",
      councilName: "Wigan",
    },
    {
      fileName: "Knowsley.jpg",
      slug: "knowsley",
      localAuthorityCountry: "eng",
      localAuthorityCode: "KWL",
      collectionDate: "16 March 2018",
      colour: "211-blue",
      councilName: "Knowsley",
    },
    {
      fileName: "Warrington.jpg",
      slug: "warrington",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WRT",
      collectionDate: "15 March 2018",
      colour: "784-grayscale",
      councilName: "Warrington",
    },
    {
      fileName: "Sefton.jpg",
      slug: "sefton",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SFT",
      collectionDate: "14 March 2018",
      colour: "735-grayscale",
      councilName: "Sefton",
    },
    {
      fileName: "Liverpool.jpg",
      slug: "liverpool",
      localAuthorityCountry: "eng",
      localAuthorityCode: "LIV",
      collectionDate: "14 March 2018",
      colour: "110-purple",
      councilName: "Liverpool",
    },
    {
      fileName: "Wirral.jpg",
      slug: "wirral",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WRL",
      collectionDate: "14 March 2018",
      colour: "710-grayscale",
      councilName: "Wirral",
    },
    {
      fileName: "St-Helens.jpg",
      slug: "st-helens",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SHN",
      collectionDate: "13 March 2018",
      colour: "630-brown",
      councilName: "St. Helens",
    },
    {
      fileName: "Luton.jpg",
      slug: "luton",
      localAuthorityCountry: "eng",
      localAuthorityCode: "LUT",
      collectionDate: "2 March 2018",
      colour: "756-grayscale",
      councilName: "Luton",
    },
    {
      fileName: "Allerdale.jpg",
      slug: "allerdale",
      localAuthorityCountry: "eng",
      localAuthorityCode: "ALL",
      collectionDate: "22 February 2018",
      colour: "730-grayscale",
      councilName: "Allerdale",
    },
    {
      fileName: "Stafford.jpg",
      slug: "stafford",
      localAuthorityCountry: "eng",
      localAuthorityCode: "STA",
      collectionDate: "21 February 2018",
      colour: "270-blue",
      councilName: "Stafford",
    },
    {
      fileName: "Reigate-and-Banstead.jpg",
      slug: "reigate-and-banstead",
      localAuthorityCountry: "eng",
      localAuthorityCode: "REI",
      collectionDate: "17 February 2018",
      colour: "642-brown",
      councilName: "Reigate and Banstead",
    },
    {
      fileName: "Tandridge.jpg",
      slug: "tandridge",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TAN",
      collectionDate: "17 February 2018",
      colour: "724-grayscale",
      councilName: "Tandridge",
    },
    {
      fileName: "Hackney.jpg",
      slug: "hackney",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HCK",
      collectionDate: "8 February 2018",
      colour: "770-grayscale",
      councilName: "Hackney",
    },
    {
      fileName: "Hertsmere.jpg",
      slug: "hertsmere",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HER",
      collectionDate: "3 February 2018",
      colour: "794-grayscale",
      councilName: "Hertsmere",
    },
    {
      fileName: "Watford.jpg",
      slug: "watford",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WAT",
      collectionDate: "3 February 2018",
      colour: "330-green",
      councilName: "Watford",
    },
    {
      fileName: "Three-Rivers.jpg",
      slug: "three-rivers",
      localAuthorityCountry: "eng",
      localAuthorityCode: "THE",
      collectionDate: "3 February 2018",
      colour: "792-grayscale",
      councilName: "Three Rivers",
    },
    {
      fileName: "Guildford.jpg",
      slug: "guildford",
      localAuthorityCountry: "eng",
      localAuthorityCode: "GRT",
      collectionDate: "13 January 2018",
      colour: "782-grayscale",
      councilName: "Guildford",
    },
    {
      fileName: "Mole-Valley.jpg",
      slug: "mole-valley",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MOL",
      collectionDate: "13 January 2018",
      colour: "789-grayscale",
      councilName: "Mole Valley",
    },
    {
      fileName: "Epsom-and-Ewell.jpg",
      slug: "epsom-and-ewell",
      localAuthorityCountry: "eng",
      localAuthorityCode: "EPS",
      collectionDate: "13 January 2018",
      colour: "350-green",
      councilName: "Epsom and Ewell",
    },
    {
      fileName: "Spelthorne.jpg",
      slug: "spelthorne",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SPE",
      collectionDate: "24 December 2017",
      colour: "313-green",
      councilName: "Spelthorne",
    },
    {
      fileName: "Tunbridge-Wells.jpg",
      slug: "tunbridge-wells",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TUN",
      collectionDate: "15 October 2017",
      colour: "624-brown",
      councilName: "Tunbridge Wells",
    },
    {
      fileName: "Maidstone.jpg",
      slug: "maidstone",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MAI",
      collectionDate: "15 October 2017",
      colour: "340-green",
      councilName: "Maidstone",
    },
    {
      fileName: "Tonbridge-and-Malling.jpg",
      slug: "tonbridge-and-malling",
      localAuthorityCountry: "eng",
      localAuthorityCode: "TON",
      collectionDate: "15 October 2017",
      colour: "788-grayscale",
      councilName: "Tonbridge and Malling",
    },
    {
      fileName: "Gravesham.jpg",
      slug: "gravesham",
      localAuthorityCountry: "eng",
      localAuthorityCode: "GRA",
      collectionDate: "15 October 2017",
      colour: "742-grayscale",
      councilName: "Gravesham",
    },
    {
      fileName: "Hammersmith-and-Fulham.jpg",
      slug: "hammersmith-and-fulham",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HMF",
      collectionDate: "12 October 2017",
      colour: "798-grayscale",
      councilName: "Hammersmith and Fulham",
    },
    {
      fileName: "St-Albans.jpg",
      slug: "st-albans",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SAL",
      collectionDate: "12 October 2017",
      colour: "360-green",
      councilName: "St Albans",
    },
    {
      fileName: "Lambeth.jpg",
      slug: "lambeth",
      localAuthorityCountry: "eng",
      localAuthorityCode: "LBH",
      collectionDate: "8 October 2017",
      colour: "743-grayscale",
      councilName: "Lambeth",
    },
    {
      fileName: "Cherwell.jpg",
      slug: "cherwell",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CHR",
      collectionDate: "7 October 2017",
      colour: "611-brown",
      councilName: "Cherwell",
    },
    {
      fileName: "Dacorum.jpg",
      slug: "dacorum",
      localAuthorityCountry: "eng",
      localAuthorityCode: "DAC",
      collectionDate: "7 October 2017",
      colour: "740-grayscale",
      councilName: "Dacorum",
    },
    {
      fileName: "Ealing.jpg",
      slug: "ealing",
      localAuthorityCountry: "eng",
      localAuthorityCode: "EAL",
      collectionDate: "1 October 2017",
      colour: "291-blue",
      councilName: "Ealing",
    },
    {
      fileName: "South-Lakeland.jpg",
      slug: "south-lakeland",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SLA",
      collectionDate: "29 August 2017",
      colour: "350-green",
      councilName: "South Lakeland",
    },
    {
      fileName: "Lancaster.jpg",
      slug: "lancaster",
      localAuthorityCountry: "eng",
      localAuthorityCode: "LAC",
      collectionDate: "29 August 2017",
      colour: "762-grayscale",
      councilName: "Lancaster",
    },
    {
      fileName: "Preston.jpg",
      slug: "preston",
      localAuthorityCountry: "eng",
      localAuthorityCode: "PRE",
      collectionDate: "29 August 2017",
      colour: "354-green",
      councilName: "Preston",
    },
    {
      fileName: "South-Ribble.jpg",
      slug: "south-ribble",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SRI",
      collectionDate: "28 August 2017",
      colour: "260-blue",
      councilName: "South Ribble",
    },
    {
      fileName: "Bolton.jpg",
      slug: "bolton",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BOL",
      collectionDate: "28 August 2017",
      colour: "400-yellow-orange",
      councilName: "Bolton",
    },
    {
      fileName: "Chorley.jpg",
      slug: "chorley",
      localAuthorityCountry: "eng",
      localAuthorityCode: "CHO",
      collectionDate: "28 August 2017",
      colour: "731-grayscale",
      councilName: "Chorley",
    },
    {
      fileName: "Birmingham.jpg",
      slug: "birmingham",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BIR",
      collectionDate: "27 August 2017",
      colour: "772-grayscale",
      councilName: "Birmingham",
    },
    {
      fileName: "Mid-Sussex.jpg",
      slug: "mid-sussex",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MSS",
      collectionDate: "30 June 2017",
      colour: "754-grayscale",
      councilName: "Mid Sussex",
    },
    {
      fileName: "Brighton-and-Hove.jpg",
      slug: "brighton-and-hove",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BNH",
      collectionDate: "30 June 2017",
      colour: "314-green",
      councilName: "Brighton and Hove",
    },
    {
      fileName: "South-Somerset.jpg",
      slug: "south-somerset",
      localAuthorityCountry: "eng",
      localAuthorityCode: "SSO",
      collectionDate: "20 June 2017",
      colour: "771-grayscale",
      councilName: "South Somerset",
    },
    {
      fileName: "Havering.jpg",
      slug: "havering",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HAV",
      collectionDate: "11 June 2017",
      colour: "342-green",
      councilName: "Havering",
    },
    {
      fileName: "Barking-and-Dagenham.jpg",
      slug: "barking-and-dagenham",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BDG",
      collectionDate: "11 June 2017",
      colour: "615-brown",
      councilName: "Barking and Dagenham",
    },
    {
      fileName: "Elmbridge.jpg",
      slug: "elmbridge",
      localAuthorityCountry: "eng",
      localAuthorityCode: "ELM",
      collectionDate: "3 June 2017",
      colour: "345-green",
      councilName: "Elmbridge",
    },
    {
      fileName: "Huntingdonshire.jpg",
      slug: "huntingdonshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HUN",
      collectionDate: "30 May 2017",
      colour: "280-blue",
      councilName: "Huntingdonshire",
    },
    {
      fileName: "Northumberland.jpg",
      slug: "northumberland",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NBL",
      collectionDate: "27 May 2017",
      colour: "603-brown",
      councilName: "Northumberland",
    },
    {
      fileName: "Milton-Keynes.jpg",
      slug: "milton-keynes",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MIK",
      collectionDate: "26 May 2017",
      colour: "310-green",
      councilName: "Milton Keynes",
    },
    {
      fileName: "Dartford.jpg",
      slug: "dartford",
      localAuthorityCountry: "eng",
      localAuthorityCode: "DAR",
      collectionDate: "21 May 2017",
      colour: "746-grayscale",
      councilName: "Dartford",
    },
    {
      fileName: "Bexley.jpg",
      slug: "bexley",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BEX",
      collectionDate: "21 May 2017",
      colour: "640-brown",
      councilName: "Bexley",
    },
    {
      fileName: "Newcastle-upon-Tyne.jpg",
      slug: "newcastle-upon-tyne",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NET",
      collectionDate: "17 May 2017",
      colour: "280-blue",
      councilName: "Newcastle upon Tyne",
    },
    {
      fileName: "North-Tyneside.jpg",
      slug: "north-tyneside",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NTY",
      collectionDate: "17 May 2017",
      colour: "300-green",
      councilName: "North Tyneside",
    },
    {
      fileName: "Harrow.jpg",
      slug: "harrow",
      localAuthorityCountry: "eng",
      localAuthorityCode: "HRW",
      collectionDate: "22 April 2017",
      colour: "635-brown",
      councilName: "Harrow",
    },
    {
      fileName: "Brent.jpg",
      slug: "brent",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BEN",
      collectionDate: "22 April 2017",
      colour: "747-grayscale",
      councilName: "Brent",
    },
    {
      fileName: "Daventry.jpg",
      slug: "daventry",
      localAuthorityCountry: "eng",
      localAuthorityCode: "DAV",
      collectionDate: "20 April 2017",
      colour: "766-grayscale",
      councilName: "Daventry",
    },
    {
      fileName: "Northampton.jpg",
      slug: "northampton",
      localAuthorityCountry: "eng",
      localAuthorityCode: "NOR",
      collectionDate: "20 April 2017",
      colour: "766-grayscale",
      councilName: "Northampton",
    },
    {
      fileName: "Enfield.jpg",
      slug: "enfield",
      localAuthorityCountry: "eng",
      localAuthorityCode: "ENF",
      collectionDate: "17 April 2017",
      colour: "775-grayscale",
      councilName: "Enfield",
    },
    {
      fileName: "Broxbourne.jpg",
      slug: "broxbourne",
      localAuthorityCountry: "eng",
      localAuthorityCode: "BRX",
      collectionDate: "17 April 2017",
      colour: "757-grayscale",
      councilName: "Broxbourne",
    },
    {
      fileName: "East-Hertsfordshire.jpg",
      slug: "east-hertsfordshire",
      localAuthorityCountry: "eng",
      localAuthorityCode: "EHE",
      collectionDate: "17 April 2017",
      colour: "722-grayscale",
      councilName: "East Hertfordshire",
    },
    {
      fileName: "Waltham-Forest.jpg",
      slug: "waltham-forest",
      localAuthorityCountry: "eng",
      localAuthorityCode: "WFT",
      collectionDate: "16 April 2017",
      colour: "780-grayscale",
      councilName: "Waltham Forest",
    },
    {
      fileName: "Renfrewshire.jpg",
      slug: "renfrewshire",
      localAuthorityCountry: "sct",
      localAuthorityCode: "RFW",
      collectionDate: "16 April 2017",
      colour: "260-blue",
      councilName: "Renfrewshire",
    },
    {
      fileName: "East-Dunbartonshire.jpg",
      slug: "east-dunbartonshire",
      localAuthorityCountry: "sct",
      localAuthorityCode: "EDU",
      collectionDate: "15 April 2017",
      colour: "401-yellow-orange",
      councilName: "East Dunbartonshire",
    },
    {
      fileName: "Stirling.jpg",
      slug: "stirling",
      localAuthorityCountry: "sct",
      localAuthorityCode: "STG",
      collectionDate: "15 April 2017",
      colour: "240-blue",
      councilName: "Stirling",
    },
    {
      fileName: "Perth-and-Kinross.jpg",
      slug: "perth-and-kinross",
      localAuthorityCountry: "sct",
      localAuthorityCode: "PKN",
      collectionDate: "15 April 2017",
      colour: "775-grayscale",
      councilName: "Perth and Kinross",
    },
    {
      fileName: "Medway.jpg",
      slug: "medway",
      localAuthorityCountry: "eng",
      localAuthorityCode: "MDW",
      collectionDate: "18 January 2017",
      colour: "623-brown",
      councilName: "Medway",
    },
  ],
};
